// <auto-generated />
using System;
using FasTnT.EfCore.Store;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FasTnT.Migrations.Postgres.Migrations
{
    [DbContext(typeof(EpcisContext))]
    [Migration("20221205130321_ViewsAndTriggers")]
    partial class ViewsAndTriggers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FasTnT.Domain.Model.CustomQueries.StoredQuery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StoredQuery", "Queries");

                    b.HasData(
                        new
                        {
                            Id = -2,
                            DataSource = "SimpleEventQuery",
                            Name = "SimpleEventQuery"
                        },
                        new
                        {
                            Id = -1,
                            DataSource = "SimpleMasterDataQuery",
                            Name = "SimpleMasterDataQuery"
                        });
                });

            modelBuilder.Entity("FasTnT.Domain.Model.CustomQueries.StoredQueryParameter", b =>
                {
                    b.Property<int>("QueryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Values")
                        .HasColumnType("text");

                    b.HasKey("QueryId", "Name");

                    b.ToTable("StoredQueryParameter", "Subscription");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.BusinessTransaction", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("EventId", "Type", "Id");

                    b.ToTable("BusinessTransaction", "Epcis");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.ContactInformation", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<short>("Type")
                        .HasMaxLength(256)
                        .HasColumnType("smallint");

                    b.Property<string>("Identifier")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Contact")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ContactTypeIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("text");

                    b.HasKey("RequestId", "Type", "Identifier");

                    b.ToTable("ContactInformation", "Sbdh");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.CorrectiveEventId", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrectiveId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("EventId", "CorrectiveId");

                    b.ToTable("CorrectiveEventId", "Epcis");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.Destination", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("EventId", "Type", "Id");

                    b.ToTable("Destination", "Epcis");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.Epc", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<float?>("Quantity")
                        .HasColumnType("real");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("EventId", "Type", "Id");

                    b.ToTable("Epc", "Epcis");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Action")
                        .HasColumnType("smallint");

                    b.Property<string>("BusinessLocation")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BusinessStep")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CaptureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CertificationInfo")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("CorrectiveDeclarationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrectiveReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Disposition")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("EventTimeZoneOffset")
                        .HasColumnType("smallint");

                    b.Property<string>("ReadPoint")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("integer");

                    b.Property<string>("TransformationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("Event", "Epcis");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.Field", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DateValue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Namespace")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("double precision");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer");

                    b.Property<int?>("SensorId")
                        .HasColumnType("integer");

                    b.Property<string>("TextValue")
                        .HasColumnType("text");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("EventId", "FieldId");

                    b.HasIndex("EventId", "ParentId");

                    b.HasIndex("EventId", "SensorId", "ReportId");

                    b.ToTable("Field", "Epcis");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.MasterData", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("RequestId", "Type", "Id");

                    b.ToTable("MasterData", "Cbv");

                    b.ToView("CurrentMasterdata", "Cbv");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.MasterDataAttribute", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<string>("MasterdataType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MasterdataId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("RequestId", "MasterdataType", "MasterdataId", "Id");

                    b.ToTable("MasterDataAttribute", "Cbv");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.MasterDataChildren", b =>
                {
                    b.Property<int?>("MasterDataRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("MasterDataType")
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MasterDataId")
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ChildrenId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("MasterDataRequestId", "MasterDataType", "MasterDataId", "ChildrenId");

                    b.ToTable("MasterDataChildren", "Cbv");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.MasterDataField", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<string>("MasterdataType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MasterdataId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AttributeId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Namespace")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParentName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParentNamespace")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("RequestId", "MasterdataType", "MasterdataId", "AttributeId", "Namespace", "Name");

                    b.ToTable("MasterDataField", "Cbv");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.MasterDataHierarchy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.Property<int?>("RequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId", "Type", "Id");

                    b.ToTable((string)null);

                    b.ToView("MasterDataHierarchy", "Cbv");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.PersistentDisposition", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("EventId", "Type", "Id");

                    b.ToTable("PersistentDisposition", "Epcis");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.SensorElement", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer");

                    b.Property<string>("BizRules")
                        .HasColumnType("text");

                    b.Property<string>("DataProcessingMethod")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceMetadata")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawData")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId", "SensorId");

                    b.ToTable("SensorElement", "Epcis");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.SensorReport", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<bool>("BooleanValue")
                        .HasColumnType("boolean");

                    b.Property<string>("ChemicalSubstance")
                        .HasColumnType("text");

                    b.Property<string>("Component")
                        .HasColumnType("text");

                    b.Property<string>("DataProcessingMethod")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceMetadata")
                        .HasColumnType("text");

                    b.Property<string>("HexBinaryValue")
                        .HasColumnType("text");

                    b.Property<float?>("MaxValue")
                        .HasColumnType("real");

                    b.Property<float?>("MeanValue")
                        .HasColumnType("real");

                    b.Property<string>("Microorganism")
                        .HasColumnType("text");

                    b.Property<float?>("MinValue")
                        .HasColumnType("real");

                    b.Property<float?>("PercRank")
                        .HasColumnType("real");

                    b.Property<float?>("PercValue")
                        .HasColumnType("real");

                    b.Property<string>("RawData")
                        .HasColumnType("text");

                    b.Property<float?>("SDev")
                        .HasColumnType("real");

                    b.Property<string>("StringValue")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("text");

                    b.Property<string>("UriValue")
                        .HasColumnType("text");

                    b.Property<float?>("Value")
                        .HasColumnType("real");

                    b.HasKey("EventId", "SensorId", "ReportId");

                    b.ToTable("SensorReport", "Epcis");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.Source", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("EventId", "Type", "Id");

                    b.ToTable("Source", "Epcis");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CaptureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CaptureId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DocumentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Request", "Epcis", t =>
                        {
                            t.HasTrigger("SubscriptionPendingRequests");
                        });
                });

            modelBuilder.Entity("FasTnT.Domain.Model.StandardBusinessHeader", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstanceIdentifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TypeVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("RequestId");

                    b.ToTable("StandardBusinessHeader", "Sbdh");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Subscriptions.PendingRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("RequestId", "SubscriptionId");

                    b.ToTable("PendingRequest", "Subscription");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Subscriptions.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .HasColumnType("text");

                    b.Property<string>("FormatterName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("InitialRecordTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("QueryId")
                        .HasColumnType("integer");

                    b.Property<string>("QueryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("ReportIfEmpty")
                        .HasColumnType("boolean");

                    b.Property<string>("SignatureToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Trigger")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("Subscription", "Subscription", t =>
                        {
                            t.HasTrigger("SubscriptionInitialRequests");
                        });
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Subscriptions.SubscriptionCallback", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<short>("CallbackType")
                        .HasColumnType("smallint");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("RequestId");

                    b.ToTable("SubscriptionCallback", "Epcis");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Subscriptions.SubscriptionExecutionRecord", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<bool>("ResultsSent")
                        .HasColumnType("boolean");

                    b.Property<bool>("Successful")
                        .HasColumnType("boolean");

                    b.HasKey("SubscriptionId", "ExecutionTime");

                    b.ToTable("SubscriptionExecutionRecord", "Subscription");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Subscriptions.SubscriptionParameter", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Values")
                        .HasColumnType("text");

                    b.HasKey("SubscriptionId", "Name");

                    b.ToTable("SubscriptionParameter", "Subscription");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Subscriptions.SubscriptionSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DayOfMonth")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DayOfWeek")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Hour")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Minute")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Month")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Second")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId")
                        .IsUnique();

                    b.ToTable("SubscriptionSchedule", "Subscription");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.CustomQueries.StoredQueryParameter", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.CustomQueries.StoredQuery", "Query")
                        .WithMany("Parameters")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.BusinessTransaction", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Events.Event", "Event")
                        .WithMany("Transactions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.ContactInformation", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.StandardBusinessHeader", "Header")
                        .WithMany("ContactInformations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.CorrectiveEventId", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Events.Event", "Event")
                        .WithMany("CorrectiveEventIds")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.Destination", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Events.Event", "Event")
                        .WithMany("Destinations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.Epc", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Events.Event", "Event")
                        .WithMany("Epcs")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.Event", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Request", "Request")
                        .WithMany("Events")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.Field", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Events.Event", "Event")
                        .WithMany("Fields")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FasTnT.Domain.Model.Events.Field", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("EventId", "ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FasTnT.Domain.Model.Events.SensorElement", "Element")
                        .WithMany("Fields")
                        .HasForeignKey("EventId", "SensorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FasTnT.Domain.Model.Events.SensorReport", "Report")
                        .WithMany("Fields")
                        .HasForeignKey("EventId", "SensorId", "ReportId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Element");

                    b.Navigation("Event");

                    b.Navigation("Parent");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.MasterData", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Request", "Request")
                        .WithMany("Masterdata")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.MasterDataAttribute", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Events.MasterData", "MasterData")
                        .WithMany("Attributes")
                        .HasForeignKey("RequestId", "MasterdataType", "MasterdataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterData");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.MasterDataChildren", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Events.MasterData", "MasterData")
                        .WithMany("Children")
                        .HasForeignKey("MasterDataRequestId", "MasterDataType", "MasterDataId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MasterData");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.MasterDataField", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Events.MasterDataAttribute", "Attribute")
                        .WithMany("Fields")
                        .HasForeignKey("RequestId", "MasterdataType", "MasterdataId", "AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.MasterDataHierarchy", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Events.MasterData", "MasterData")
                        .WithMany("Hierarchies")
                        .HasForeignKey("RequestId", "Type", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MasterData");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.PersistentDisposition", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Events.Event", "Event")
                        .WithMany("PersistentDispositions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.SensorElement", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Events.Event", "Event")
                        .WithMany("SensorElements")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.SensorReport", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Events.SensorElement", "SensorElement")
                        .WithMany("Reports")
                        .HasForeignKey("EventId", "SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorElement");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.Source", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Events.Event", "Event")
                        .WithMany("Sources")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.StandardBusinessHeader", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Request", "Request")
                        .WithOne("StandardBusinessHeader")
                        .HasForeignKey("FasTnT.Domain.Model.StandardBusinessHeader", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Subscriptions.Subscription", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.CustomQueries.StoredQuery", "Query")
                        .WithMany("Subscriptions")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Query");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Subscriptions.SubscriptionCallback", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Request", "Request")
                        .WithOne("SubscriptionCallback")
                        .HasForeignKey("FasTnT.Domain.Model.Subscriptions.SubscriptionCallback", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Subscriptions.SubscriptionExecutionRecord", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Subscriptions.Subscription", "Subscription")
                        .WithMany("ExecutionRecords")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Subscriptions.SubscriptionParameter", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Subscriptions.Subscription", "Subscription")
                        .WithMany("Parameters")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Subscriptions.SubscriptionSchedule", b =>
                {
                    b.HasOne("FasTnT.Domain.Model.Subscriptions.Subscription", "Subscription")
                        .WithOne("Schedule")
                        .HasForeignKey("FasTnT.Domain.Model.Subscriptions.SubscriptionSchedule", "SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.CustomQueries.StoredQuery", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.Event", b =>
                {
                    b.Navigation("CorrectiveEventIds");

                    b.Navigation("Destinations");

                    b.Navigation("Epcs");

                    b.Navigation("Fields");

                    b.Navigation("PersistentDispositions");

                    b.Navigation("SensorElements");

                    b.Navigation("Sources");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.Field", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.MasterData", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Children");

                    b.Navigation("Hierarchies");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.MasterDataAttribute", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.SensorElement", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Events.SensorReport", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Request", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Masterdata");

                    b.Navigation("StandardBusinessHeader");

                    b.Navigation("SubscriptionCallback");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.StandardBusinessHeader", b =>
                {
                    b.Navigation("ContactInformations");
                });

            modelBuilder.Entity("FasTnT.Domain.Model.Subscriptions.Subscription", b =>
                {
                    b.Navigation("ExecutionRecords");

                    b.Navigation("Parameters");

                    b.Navigation("Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
